// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-asset-images.js
// Run "bun run scripts/generate-asset-images.js" to regenerate

// Asset images that are bundled with the app
// These images are available to all users (synced via the app bundle)

export const ASSET_IMAGES: Record<string, number> = {
  // Image images
  'image-1768006466': require('../../assets/image-1768006466.jpeg'),
  'image-1767902007': require('../../assets/image-1767902007.png'),
  'image-1767787667': require('../../assets/image-1767787667.png'),
  'image-1768006432': require('../../assets/image-1768006432.jpeg'),
  'image-1767960627': require('../../assets/image-1767960627.jpeg'),
  'image-1767999488': require('../../assets/image-1767999488.jpeg'),
  'image-1768000966': require('../../assets/image-1768000966.jpeg'),
  'image-1767811319': require('../../assets/image-1767811319.jpeg'),
  'image-1767787654': require('../../assets/image-1767787654.png'),
  'image-1767817595': require('../../assets/image-1767817595.jpeg'),
  'image-1767811691': require('../../assets/image-1767811691.jpeg'),
  'image-1767960656': require('../../assets/image-1767960656.jpeg'),
  'image-1767901601': require('../../assets/image-1767901601.png'),
  'image-1768000740': require('../../assets/image-1768000740.png'),
  'image-1767999438': require('../../assets/image-1767999438.jpeg'),
  'image-1767999538': require('../../assets/image-1767999538.jpeg'),
  'image-1768006399': require('../../assets/image-1768006399.jpeg'),
  'image-1768000725': require('../../assets/image-1768000725.jpeg'),
  'image-1767999599': require('../../assets/image-1767999599.jpeg'),
  'image-1767999578': require('../../assets/image-1767999578.jpeg'),
  'image-1767896795': require('../../assets/image-1767896795.jpeg'),
  'image-1767796413': require('../../assets/image-1767796413.jpeg'),
  'image-1767960592': require('../../assets/image-1767960592.jpeg'),
  'image-1767796415': require('../../assets/image-1767796415.jpeg'),
  'image-1767960643': require('../../assets/image-1767960643.jpeg'),
  'image-1767999373': require('../../assets/image-1767999373.png'),
  'image-1767999362': require('../../assets/image-1767999362.png'),
  'image-1768001029': require('../../assets/image-1768001029.jpeg'),
  'image-1767822177': require('../../assets/image-1767822177.png'),
  'image-1767999565': require('../../assets/image-1767999565.jpeg'),
  'image-1767999510': require('../../assets/image-1767999510.jpeg'),
  'image-1767999459': require('../../assets/image-1767999459.jpeg'),
  'image-1768037045': require('../../public/image-1768037045.jpeg'),

  // Background images
  'background-1767792528504': require('../../assets/background-1767792528504.png'),
  'background-1767873213701': require('../../assets/background-1767873213701.png'),

  // Icon images
  'icon-1767787718705': require('../../assets/icon-1767787718705.png'),
  'icon-1767888757342': require('../../assets/icon-1767888757342.png'),

  // Other images
  'other-1768002161924': require('../../assets/other-1768002161924.png'),
  '400569412-208406268957629-3547887922091756068-n': require('../../public/400569412-208406268957629-3547887922091756068-n.jpeg'),

};

// All asset IDs
export const ALL_ASSET_IDS = Object.keys(ASSET_IMAGES);

// Category arrays for filtering
export const IMAGE_ASSET_IDS = ALL_ASSET_IDS.filter(id => id.startsWith('image-'));
export const BACKGROUND_ASSET_IDS = ALL_ASSET_IDS.filter(id => id.startsWith('background-'));
export const ICON_ASSET_IDS = ALL_ASSET_IDS.filter(id => id.startsWith('icon-'));
export const LOGO_ASSET_IDS = ALL_ASSET_IDS.filter(id => id.startsWith('logo-'));

// Legacy exports for backward compatibility
export const PACK_ASSET_IDS = IMAGE_ASSET_IDS.slice(0, 10);
export const PRODUCER_ASSET_IDS = IMAGE_ASSET_IDS.slice(0, 4);
export const FIELD_ASSET_IDS = IMAGE_ASSET_IDS.slice(0, 6);
export const ILLUSTRATION_ASSET_IDS = IMAGE_ASSET_IDS.slice(0, 3);

// Get the image source for a given image string
// Handles both asset: prefixed strings and regular URLs
export function getImageSource(image: string | undefined | null): number | { uri: string } | undefined {
  if (!image) {
    return undefined;
  }
  if (image.startsWith('asset:')) {
    const assetId = image.replace('asset:', '');
    const assetSource = ASSET_IMAGES[assetId];
    if (assetSource) {
      return assetSource;
    }
  }
  return { uri: image };
}

// Check if an image is an asset image
export function isAssetImage(image: string): boolean {
  return image.startsWith('asset:');
}
